/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "brand-red": "hsl(var(--brand-red))",
        "brand-dark": "hsl(var(--brand-dark))",
        "nav-text": "hsl(var(--nav-text))",
        "nav-border": "hsl(var(--nav-border))",
        "pet-blue": "#4962AA",
        "pet-blue-light": "#E4EEFE",
        "pet-bg": "#FAFAFA",
        "pet-stroke": "#E9EAEE",
        "pet-black": "#25272C",
        "pet-gray": "#6B7280",
        "pet-input-bg": "#F9FAFB",
        "pet-input-border": "#E5E7EB",
        "pet-placeholder": "#909EAA",
        "pet-gray-dark": "#70747B",
        "pet-gray-darker": "#474B52",
        "pet-green": "#509874",
        "pet-divider": "#F3F4F6",
        "pet-body": "#364153",
        "pet-verified-text": "#9FDDB9",
        "pet-verified-muted": "#9BB7A9",
        "pet-verified-border": "#6E917F",
        "pet-tag-bg": "#E8ECF0",
        "pet-tag-text": "#747784",
        "pet-check-green": "#2CAC61",
        "pet-check-dark": "#00A63E",
        "pet-red": "#FB461E",
        "brand-blue": "#4962AA",
        "brand-black": "#25272C",
        "brand-gray-dark": "#474B52",
        "brand-gray-medium": "#70747B",
        "brand-gray": "#8D93A2",
        "brand-gray-bg": "#F6F7F8",
        "brand-stroke": "#E9EAEE",
        "gvd-blue": "#4962AA",
        "gvd-dark": "#364153",
        "gvd-dark-2": "#6B7280",
        "gvd-gray-3": "#909EAA",
        "gvd-stroke": "#E9EAEE",
        "gvd-black": "#25272C",
        "gvd-star": "#FFB900",
        "gvd-subtitle": "#9C9EA3",
        "gvd-gray-dark-3": "#576271",
        "gvd-page-bg": "#F5F7FA",
        "health-green": "#638775",
        "health-green-dark": "#4B7761",
        "health-green-light": "#E4FAED",
        "adopt-blue": "#4962AA",
        "adopt-black": "#25272C",
        "adopt-gray-dark": "#576271",
        "adopt-gray-muted": "#9EA3AC",
        "adopt-stroke": "#E9EAEE",
        "adopt-text-dark": "#364153",
        "chip-warn-bg": "#FCEBE6",
        "chip-warn-text": "#D93F53",
        "chip-akc-bg": "#E8F5EC",
        "chip-akc-text": "#2B7A3B",
        "chip-exp-bg": "#EFF3FF",
        "chip-exp-text": "#4A5FAD",
      },
      fontFamily: {
        sans: ["var(--font-poppins)", "sans-serif"],
        poppins: ["var(--font-poppins)", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      boxShadow: {
        card: "10px 10px 60px 0 rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
}